<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Your Addresses_ya-myab-plus-address-icon</name>
   <tag></tag>
   <elementGuidId>7b825dbd-9d9e-4d12-9fa1-0932a2658f6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ya-myab-plus-address-icon']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ya-myab-plus-address-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>46521c91-bea3-4ce5-aa89-7b1acd121b2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ya-myab-plus-address-icon</value>
      <webElementGuid>1c7b0926-ee5a-4ef7-a9ec-2c1754f81400</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-section a-spacing-none address-plus-icon aok-inline-block</value>
      <webElementGuid>67aaf0ed-2ef7-4432-9f35-cfed59629e04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ya-myab-plus-address-icon&quot;)</value>
      <webElementGuid>5ececda7-3fa2-42c5-8b1d-c836c3e9e01a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ya-myab-plus-address-icon']</value>
      <webElementGuid>352173e3-5251-452c-bad6-622d251728ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='ya-myab-address-add-link']/div/div/div</value>
      <webElementGuid>fbdc75d8-72b9-4017-b49d-d4026f72547d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/div/div</value>
      <webElementGuid>eadd5cb5-deaf-4067-a02b-21e84fd2a75a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ya-myab-plus-address-icon']</value>
      <webElementGuid>fef527c4-9a07-4e6b-9565-1e07e60ef4a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
