<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Full name (First and Last name)_addre_efd85e</name>
   <tag></tag>
   <elementGuidId>f5d31a40-e3ae-4102-84d5-5631c6bcb6be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='address-ui-widgets-enterAddressFullName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#address-ui-widgets-enterAddressFullName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>395b208e-bf29-4679-9efa-163261081e25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a5f1dc1c-bd59-4832-8a93-9de1901f8ae2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>2de310ef-1b17-40d0-968f-e37f3769abe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>address-ui-widgets-enterAddressFullName</value>
      <webElementGuid>ecac7c26-17a8-4773-b35c-4ff28be3f912</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>address-ui-widgets-enterAddressFullName</value>
      <webElementGuid>3a4a481a-218a-4147-ba23-a0b1aafaf941</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>00351e37-382a-48ad-a116-48079898e5df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-input-text address-ui-widgets-desktop-form-field-full-width addrui-form-text-input</value>
      <webElementGuid>cc78ffe4-b918-4c3f-89a0-48e8c207f8a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address-ui-widgets-enterAddressFullName&quot;)</value>
      <webElementGuid>dcbaed0c-b191-483f-9aab-d8a2c23c55ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='address-ui-widgets-enterAddressFullName']</value>
      <webElementGuid>8a4bf31c-bd60-4966-a281-c0292d58dd4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='address-ui-widgets-enterAddressFormContainer']/div[7]/div/div[4]/input</value>
      <webElementGuid>34033752-c398-4666-94f0-c8e96da5f471</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>2b5d4851-3821-42f8-a2c2-15a928030527</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'address-ui-widgets-enterAddressFullName' and @name = 'address-ui-widgets-enterAddressFullName']</value>
      <webElementGuid>6c9c7df8-4676-4560-96e3-a7e56bec9043</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
