<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Zip Code_address-ui-widgets-enterAddr_79805c</name>
   <tag></tag>
   <elementGuidId>55836ad7-5106-4fd3-acea-fcd59e4fad97</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='address-ui-widgets-enterAddressPostalCode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#address-ui-widgets-enterAddressPostalCode</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>71304073-8c18-4e4b-a384-472283c531d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cb3e93f1-7f6d-4562-aaf9-09ca552c564c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>55c2a38f-0377-4483-9376-5824ea95dfa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>address-ui-widgets-enterAddressPostalCode</value>
      <webElementGuid>f31c7a31-39d2-4bc4-bbea-190812dd2ffe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>address-ui-widgets-enterAddressPostalCode</value>
      <webElementGuid>b6270ef7-cdbe-44ca-87d5-781f94600de1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>788528c7-dbc4-4e2c-999f-7b98034a62fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-input-text address-ui-widgets-desktop-form-field-full-width addrui-form-text-input</value>
      <webElementGuid>dad45c85-1838-4354-b031-fcb57d8e5f08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address-ui-widgets-enterAddressPostalCode&quot;)</value>
      <webElementGuid>e1d7c406-3420-41a6-8116-8d4e3acaad29</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='address-ui-widgets-enterAddressPostalCode']</value>
      <webElementGuid>1bcc32e8-6e0e-4173-ac66-11507839a161</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='address-ui-widgets-enterAddressFormContainer']/div[7]/div/div[14]/input</value>
      <webElementGuid>0c013509-a10d-47bd-8eed-460ff7992f9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/input</value>
      <webElementGuid>fb98f82b-6c98-44ad-8c33-fe3477aabe6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'address-ui-widgets-enterAddressPostalCode' and @name = 'address-ui-widgets-enterAddressPostalCode']</value>
      <webElementGuid>354e0746-2994-4d8b-8f86-dcd5a2439132</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
