<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Rushikesh_name-edit-pencil-image</name>
   <tag></tag>
   <elementGuidId>276a7229-29de-4dae-8e10-b981da778bf5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='name-edit-pencil-image']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#name-edit-pencil-image</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7ee6cf94-f932-4cf3-9fc0-ea1977b01808</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Link to edit profile name</value>
      <webElementGuid>3565bf63-2671-4100-b19a-9b4d7605e2c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://m.media-amazon.com/images/G/01/Beerus-MY/pencil.png</value>
      <webElementGuid>607c6887-3a23-4cad-a732-fff88d8c493d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>name-edit-icon</value>
      <webElementGuid>0cc27ab4-648e-42fe-a253-318129b6a110</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>name-edit-pencil-image</value>
      <webElementGuid>ef8b4d97-f6ac-4e8b-99f3-9cd901ec8ee9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;name-edit-pencil-image&quot;)</value>
      <webElementGuid>55352dde-e897-475f-be3c-e7c23c6f20e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='name-edit-pencil-image']</value>
      <webElementGuid>e296154a-7f5d-4c70-8ed9-4259af71ad4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='name-edit-modal-link']/img</value>
      <webElementGuid>c6881f3f-a207-40a8-9906-f7dc5cc59153</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Link to edit profile name']</value>
      <webElementGuid>5a750ca6-1de4-49cc-a616-fe7c773c5d3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img</value>
      <webElementGuid>1deba4b4-18ec-43cb-941c-538c874666ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Link to edit profile name' and @src = 'https://m.media-amazon.com/images/G/01/Beerus-MY/pencil.png' and @id = 'name-edit-pencil-image']</value>
      <webElementGuid>91b20e3d-d593-45a6-83e2-35a3cf35380e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
