<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Edit your name_profile-name-text-input</name>
   <tag></tag>
   <elementGuidId>02fe48ac-b852-4ef7-90c7-7af5bf73616b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='profile-name-text-input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#profile-name-text-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8471d182-8751-4f43-920c-ac22240817c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>87416c0a-9504-4149-855e-20d8b1d4a750</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Rushikesh</value>
      <webElementGuid>61117a4f-872f-488f-9070-e95a69b86041</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profile-name-text-input</value>
      <webElementGuid>2573652f-8990-4e6e-892e-2e739023dd1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ea0b4564-b426-4d1a-aaf3-4ddde7e31287</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Name</value>
      <webElementGuid>4b062b64-5912-4e46-ae69-5cc76ab5e5c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>profile-name-text-input</value>
      <webElementGuid>b124753d-fb7e-4454-a938-987e9cfaf409</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-input-text a-span12</value>
      <webElementGuid>2ac14d6e-8213-482b-b4dc-b4e3cf53afe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profile-name-text-input&quot;)</value>
      <webElementGuid>125a5ae9-bc2b-4933-97d9-5ac9afb78239</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='profile-name-text-input']</value>
      <webElementGuid>5f201a4e-51e7-4ffd-a142-bad067decdda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='profile-name-edit-section']/input[3]</value>
      <webElementGuid>e7fcef02-fc75-48c4-be62-e55825405c98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/input[3]</value>
      <webElementGuid>2700b548-582f-4034-a871-72900a5ea16d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'profile-name-text-input' and @placeholder = 'Name' and @name = 'profile-name-text-input']</value>
      <webElementGuid>f32cdb44-82ae-4812-b349-65e88b50e0b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
