<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Rushikesh Ingale_name-edit-pencil-image</name>
   <tag></tag>
   <elementGuidId>6203ec9b-0d24-4f84-93f9-c6c76a4f1592</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='name-edit-pencil-image']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#name-edit-pencil-image</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>389224bb-6a83-4354-9096-5e9515c7de2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Link to edit profile name</value>
      <webElementGuid>29205d6e-bcb6-444f-b2b0-2ef6d91011f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://m.media-amazon.com/images/G/01/Beerus-MY/pencil.png</value>
      <webElementGuid>99e4560c-4e30-4d43-827b-65210f8e0ab6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>name-edit-icon</value>
      <webElementGuid>1245078f-4f77-4be5-95c9-56e5800cb6b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>name-edit-pencil-image</value>
      <webElementGuid>4d58ddcd-0e5c-4f96-bd49-4e473bd3e649</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;name-edit-pencil-image&quot;)</value>
      <webElementGuid>3a4aa2b0-a21e-46a9-9980-288d22fc5851</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='name-edit-pencil-image']</value>
      <webElementGuid>d4420c62-cdac-49a6-8ec6-b92ff3ef14aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='name-edit-modal-link']/img</value>
      <webElementGuid>1ea15139-07c5-437a-972a-89a93eab6421</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Link to edit profile name']</value>
      <webElementGuid>31e4d6c2-4a21-4785-9496-3bab9a1d906f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img</value>
      <webElementGuid>47ef8182-fbba-4560-8997-1c7f887132bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Link to edit profile name' and @src = 'https://m.media-amazon.com/images/G/01/Beerus-MY/pencil.png' and @id = 'name-edit-pencil-image']</value>
      <webElementGuid>efd613d5-af9c-4a03-9d75-ecef4fec2afb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
