<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Edit your name_profile-name-text-input</name>
   <tag></tag>
   <elementGuidId>6db22af9-3232-4f07-aff7-30ae599c0cec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='profile-name-text-input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#profile-name-text-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e26cffdd-0754-4f8f-85bb-e9e3912fd062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>58b758b8-848e-4459-baa1-46e2518013ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Rushikesh Ingale</value>
      <webElementGuid>ba57ce69-ede9-4ca2-94a2-28b72b8f8270</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profile-name-text-input</value>
      <webElementGuid>adebd0fc-3f81-4c15-9859-8d816623beb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f53358c5-e5ed-47b6-aaff-e76f039d1315</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Name</value>
      <webElementGuid>b5b0aad3-ef9d-43c0-b986-31dfba406147</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>profile-name-text-input</value>
      <webElementGuid>6e969ed0-e442-4088-a25e-7f33d7279ea7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-input-text a-span12</value>
      <webElementGuid>07428784-2f6e-4509-bee1-3900459c4d54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profile-name-text-input&quot;)</value>
      <webElementGuid>00e55196-44f8-456e-93ad-95d48f8af792</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='profile-name-text-input']</value>
      <webElementGuid>13e9e4d2-e90f-4c4f-b598-19046e52db6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='profile-name-edit-section']/input[3]</value>
      <webElementGuid>3c6fbf24-4b48-4667-ada0-d9b359f7648e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/input[3]</value>
      <webElementGuid>1184b797-a11f-4869-a868-4ee2746e2564</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'profile-name-text-input' and @placeholder = 'Name' and @name = 'profile-name-text-input']</value>
      <webElementGuid>b16563ac-199f-4f6d-a15e-7e23c18916be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
