<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Atomic Habits An Easy  Proven Way to Bu_65f9e7</name>
   <tag></tag>
   <elementGuidId>a0ff6e24-9723-4d93-b1fd-0423f0c505bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#p13n-asin-index-1 > div.p13n-sc-uncoverable-faceout > span.a-size-small > div.p13n-sc-truncate-desktop-type2.p13n-sc-truncated</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='p13n-asin-index-1']/div/span/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>315a30c5-ff3a-41f1-90e0-35a494edab78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p13n-sc-truncate-desktop-type2  p13n-sc-truncated</value>
      <webElementGuid>d1506a8e-3ec7-4bad-9ada-5e17ac9717bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fedff07d-e6bb-4b04-9ea1-2e9ae051e0eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>be024f5d-2bd1-400f-9e7b-70b339290316</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Atomic Habits: An Easy &amp; Proven Way to Build Good Habits &amp; Break Bad Ones</value>
      <webElementGuid>84b49398-7f3c-4dba-811c-8683c0903137</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;p13n-asin-index-1&quot;)/div[@class=&quot;p13n-sc-uncoverable-faceout&quot;]/span[@class=&quot;a-size-small&quot;]/div[@class=&quot;p13n-sc-truncate-desktop-type2  p13n-sc-truncated&quot;]</value>
      <webElementGuid>93fa403a-a581-41aa-a678-0541da7a5f88</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='p13n-asin-index-1']/div/span/div</value>
      <webElementGuid>8fdc08ba-2e0b-4c74-97ca-d7184f37337c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/span/div</value>
      <webElementGuid>faab00f3-f14e-464b-b527-4d56f6c41929</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Atomic Habits: An Easy &amp; Proven Way to Build Good Habits &amp; Break Bad Ones' or . = 'Atomic Habits: An Easy &amp; Proven Way to Build Good Habits &amp; Break Bad Ones')]</value>
      <webElementGuid>0a13aebc-a52c-4cf9-b21a-6df676db394c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
