<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_submit.addToCart</name>
   <tag></tag>
   <elementGuidId>e40fe093-fb38-496f-b0b8-ffb50e6b1d2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;submit.addToCart&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='submit.addToCart']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cb4aa974-8621-41d3-9efc-d9d2bd52ca9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>32b0fcbf-8220-40ec-aa8c-19a852b334e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>submit.addToCart</value>
      <webElementGuid>a7a93fd9-f184-4110-b3ca-d4ddde506e5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-asins</name>
      <type>Main</type>
      <value>[&quot;0735211299&quot;]</value>
      <webElementGuid>73c592e7-a37c-4f58-9d99-631af5f7f75e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mix-operations</name>
      <type>Main</type>
      <value>AddToCart</value>
      <webElementGuid>83850b6b-a26e-4879-9ddd-0a1e218ee3cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-numitems</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>95c83130-9b36-4517-82b0-234792ab5e14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-reftag</name>
      <type>Main</type>
      <value>zg_d_sccl_2_atc_a</value>
      <webElementGuid>23a5e706-4387-4bae-a546-6d88594c630b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-url</name>
      <type>Main</type>
      <value>/cart/add-to-cart/ref=zg_d_sccl_2_atc_a?_encoding=UTF8&amp;pd_rd_i=0735211299&amp;pd_rd_w=Q4Cic&amp;pf_rd_p=193afb92-0c19-4833-86f8-850b5ba40291&amp;pf_rd_r=NNHR1EWNE9QTHJDWED1D&amp;pd_rd_wg=iFDYG&amp;pd_rd_r=59933989-fc73-4949-9f40-24a63c6a6248&amp;content-id=amzn1.sym.193afb92-0c19-4833-86f8-850b5ba40291</value>
      <webElementGuid>3270fd2b-3633-427d-b9af-94698225ae8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-input</value>
      <webElementGuid>5308f0ca-bfb7-4d98-99be-6818c373c92a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AddToCartLibrary-AddToCartButton-Personalization&quot;)/span[@class=&quot;a-button a-button-primary a-button-small a-button-icon add-to-cart-button a-button-focus&quot;]/span[@class=&quot;a-button-inner&quot;]/input[@class=&quot;a-button-input&quot;]</value>
      <webElementGuid>58f7ffb6-57e1-4f99-ac9b-a94eb3074db5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='submit.addToCart']</value>
      <webElementGuid>9a39aaab-366a-4e6a-a276-54d3c3d013cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AddToCartLibrary-AddToCartButton-Personalization']/span/span/input</value>
      <webElementGuid>1c944a7d-cc8b-4add-9c77-e85c7899deb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/input</value>
      <webElementGuid>0dbc862d-4f47-46dc-82ec-25f1839a27f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'submit.addToCart']</value>
      <webElementGuid>5614c548-5dfa-4650-80fe-a1dc74fc0516</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
