<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_a-dynamic-image p13n-sc-dynamic-image p_302d0a</name>
   <tag></tag>
   <elementGuidId>6d68622f-d5e8-4c25-8088-dd74dce4a77f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#p13n-asin-index-1 > div.p13n-sc-uncoverable-faceout > div.a-section.a-spacing-mini._cDEzb_noop_3Xbw5 > img.a-dynamic-image.p13n-sc-dynamic-image.p13n-product-image</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='p13n-asin-index-1']/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e8d86c49-6e1c-4d50-a409-54ccebb1fa34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Atomic Habits: An Easy &amp; Proven Way to Build Good Habits &amp; Break Bad Ones</value>
      <webElementGuid>0f20b8b0-2e22-4838-9401-c2194724e6c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://images-na.ssl-images-amazon.com/images/I/81YkqyaFVEL._AC_UL381_SR381,381_.jpg</value>
      <webElementGuid>3297c03a-13c9-4ce5-b61f-1ed94219a0ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-dynamic-image p13n-sc-dynamic-image p13n-product-image</value>
      <webElementGuid>ac9e7761-b522-4f28-a4ff-ebc68566a44c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>127px</value>
      <webElementGuid>fb49a2c8-59cb-42f6-a975-75081815439a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-a-dynamic-image</name>
      <type>Main</type>
      <value>{&quot;https://images-na.ssl-images-amazon.com/images/I/81YkqyaFVEL._AC_UL127_SR127,127_.jpg&quot;:[127,127],&quot;https://images-na.ssl-images-amazon.com/images/I/81YkqyaFVEL._AC_UL254_SR254,254_.jpg&quot;:[254,254],&quot;https://images-na.ssl-images-amazon.com/images/I/81YkqyaFVEL._AC_UL381_SR381,381_.jpg&quot;:[381,381]}</value>
      <webElementGuid>3182f82f-a427-48c1-a1da-9d146be36529</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;p13n-asin-index-1&quot;)/div[@class=&quot;p13n-sc-uncoverable-faceout&quot;]/div[@class=&quot;a-section a-spacing-mini _cDEzb_noop_3Xbw5&quot;]/img[@class=&quot;a-dynamic-image p13n-sc-dynamic-image p13n-product-image&quot;]</value>
      <webElementGuid>db26fb95-d08c-44d3-9e10-658b18c9ddf0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='p13n-asin-index-1']/div/div/img</value>
      <webElementGuid>5382a619-6ce2-4629-9db8-365d93dae3b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Atomic Habits: An Easy &amp; Proven Way to Build Good Habits &amp; Break Bad Ones'])[2]</value>
      <webElementGuid>9c08466e-b200-4968-91fe-c44ebb6e5e9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/img</value>
      <webElementGuid>a94cef4c-df37-44d8-b4e2-4a83172f5e82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Atomic Habits: An Easy &amp; Proven Way to Build Good Habits &amp; Break Bad Ones' and @src = 'https://images-na.ssl-images-amazon.com/images/I/81YkqyaFVEL._AC_UL381_SR381,381_.jpg']</value>
      <webElementGuid>79258b54-64a7-4678-bda9-6cf090573b1a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
