<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Deleted</name>
   <tag></tag>
   <elementGuidId>7f488a77-ec78-4879-b81b-7b086d758d27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.a-box.a-alert-inline.a-alert-inline-success > div.a-box-inner.a-alert-container > div.a-alert-content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='item_I33DCY42UJRQQ1']/div[2]/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fe0e8c8c-0235-4772-9a0d-49b072598731</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-alert-content</value>
      <webElementGuid>bbef305b-d150-45ac-a6f5-3c08ed9b485c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Deleted</value>
      <webElementGuid>91198f21-fafa-4b0e-9163-7990612372b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;item_I33DCY42UJRQQ1&quot;)/div[@class=&quot;a-row a-spacing-none&quot;]/div[@class=&quot;a-box a-alert-inline a-alert-inline-success&quot;]/div[@class=&quot;a-box-inner a-alert-container&quot;]/div[@class=&quot;a-alert-content&quot;]</value>
      <webElementGuid>377117cb-8294-441f-9e9e-f100c36e83ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='item_I33DCY42UJRQQ1']/div[2]/div/div/div</value>
      <webElementGuid>8a49813d-fea8-4b01-87d7-f86f81099787</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/div[2]/div/div/div</value>
      <webElementGuid>f451d8fd-b427-4e21-a9a6-be9745783de1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Deleted' or . = 'Deleted')]</value>
      <webElementGuid>966cf307-275f-425c-878a-63e3adb9f7ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
