<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Manage your Profiles_home-profile-arrow-i_1a3f4b</name>
   <tag></tag>
   <elementGuidId>8e486fd5-a1c8-4abf-97c1-b28f07bb9758</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='home-profile-arrow-icon-active']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#home-profile-arrow-icon-active</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>0779bb7d-eb5d-4cf9-a752-362f4ae8a39a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>home-profile-arrow-icon-active</value>
      <webElementGuid>4c5174ae-f5a8-41af-ac51-7c1c00a2c847</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-icon a-icon-arrow</value>
      <webElementGuid>d60db875-1d94-4cba-b191-e88a5cf3f46e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>fc4b33d4-2863-408b-9ed3-9c9b351224a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Arrow icon for profile detail</value>
      <webElementGuid>0ae37ff8-55ba-452f-8f3b-b2f91778026f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home-profile-arrow-icon-active&quot;)</value>
      <webElementGuid>4c906728-cc3a-4791-bdfa-f6b70e22c052</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='home-profile-arrow-icon-active']</value>
      <webElementGuid>9b209de0-00b5-4aee-8b2d-00f7d94c0160</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='profile-pick-actor-button-active']/a/div/div[2]/i</value>
      <webElementGuid>073783a4-bcea-435a-9503-b14b58f7f6d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/i</value>
      <webElementGuid>1ae08e01-6823-4654-8765-39a56bf79a93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@id = 'home-profile-arrow-icon-active']</value>
      <webElementGuid>92d4cec6-d09d-45d9-b54c-34d3cba6a77f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
