<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_The Da Vinci Code (Robert Langdon)</name>
   <tag></tag>
   <elementGuidId>2415f350-3703-406a-bd6c-7c3c6d76bfa6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='p13n-asin-index-0']/div/a[2]/span/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div._cDEzb_p13n-sc-css-line-clamp-1_1Fn1y.p13n-sc-truncate-fallback.p13n-sc-line-clamp-1.p13n-sc-truncate-desktop-type2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9f90fee2-d685-4c08-9424-85ca3b4fabb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>797cfcfa-bf16-4398-9437-ac4dce7afbab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_cDEzb_p13n-sc-css-line-clamp-1_1Fn1y p13n-sc-truncate-fallback p13n-sc-line-clamp-1 p13n-sc-truncate-desktop-type2</value>
      <webElementGuid>3cc3e5ce-c7cc-4706-91a2-fab71d8783f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rows</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>cb6a2b56-01dc-4e24-8d36-26ce3a740673</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>The Da Vinci Code (Robert Langdon)</value>
      <webElementGuid>8c760dd0-c11d-48aa-baee-7ecb1b8ded57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;p13n-asin-index-0&quot;)/div[@class=&quot;p13n-sc-uncoverable-faceout&quot;]/a[@class=&quot;a-link-normal&quot;]/span[1]/div[@class=&quot;_cDEzb_p13n-sc-css-line-clamp-1_1Fn1y p13n-sc-truncate-fallback p13n-sc-line-clamp-1 p13n-sc-truncate-desktop-type2&quot;]</value>
      <webElementGuid>744bf129-6a95-4e0a-a43c-2977a5239f95</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='p13n-asin-index-0']/div/a[2]/span/div</value>
      <webElementGuid>7879cd69-31b3-4c6a-b597-21e9f82eb14d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You have no recently viewed items.'])[1]/following::div[10]</value>
      <webElementGuid>8c560b29-fba8-4943-a702-2216dbc610c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Something went wrong. Please try again.'])[1]/following::div[15]</value>
      <webElementGuid>68e5daa7-4a06-462e-ad42-9b1bd1131969</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dan Brown'])[1]/preceding::div[1]</value>
      <webElementGuid>d961dd6a-193a-4a17-a0ac-82fb17d5c569</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hardcover'])[1]/preceding::div[5]</value>
      <webElementGuid>fa0ee72c-6347-4997-a04c-e5d38bf9bcac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='The Da Vinci Code (Robert Langdon)']/parent::*</value>
      <webElementGuid>1bc8c126-f09b-4a79-869b-b7722e84668d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/span/div</value>
      <webElementGuid>382e1812-b83d-495a-a453-db3e5d668d9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'The Da Vinci Code (Robert Langdon)' or . = 'The Da Vinci Code (Robert Langdon)')]</value>
      <webElementGuid>d1efd528-1045-4cba-9b71-154b9c866616</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
