<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Edit</name>
   <tag></tag>
   <elementGuidId>caaa0637-32ea-467e-b235-cb0a78b883c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='PASSWORD_BUTTON']/span/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#PASSWORD_BUTTON > span.a-button-inner > a.a-button-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4634142f-76cd-485d-a48b-5bcb166aa482</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/ap/profile/password?ref_=ax_am_landing_change_password&amp;openid.assoc_handle=usflex</value>
      <webElementGuid>05282119-bf16-403b-b8cf-aebd31b4fdc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Edit password</value>
      <webElementGuid>fd4c504f-9e31-484f-8347-d80dbe0c2eea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-text</value>
      <webElementGuid>a3a6e5fa-8f19-4113-945b-596fde8652e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>1d1a6681-c811-4230-9fac-7ab4e5358977</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PASSWORD_BUTTON&quot;)/span[@class=&quot;a-button-inner&quot;]/a[@class=&quot;a-button-text&quot;]</value>
      <webElementGuid>854a76cb-7822-4b76-a4d8-ae99f6987adf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='PASSWORD_BUTTON']/span/a</value>
      <webElementGuid>9bc2b096-3fbc-4711-9a56-2e6d28407712</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Edit')])[3]</value>
      <webElementGuid>f6260305-29be-46bb-aa83-0c3434af676b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='**********'])[1]/following::a[1]</value>
      <webElementGuid>9b4660bc-426f-4dc6-947a-b99bd4edf899</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::a[1]</value>
      <webElementGuid>f709be5d-8767-4bbe-9947-7bde580f4c72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add a layer of security. Require a code in addition to your password.'])[1]/preceding::a[1]</value>
      <webElementGuid>763d1a84-87f6-43bf-b1b8-f8702f0c4e55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Turn on'])[1]/preceding::a[1]</value>
      <webElementGuid>b80fceb9-b3b5-486f-93ca-885c1741cbb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/ap/profile/password?ref_=ax_am_landing_change_password&amp;openid.assoc_handle=usflex')]</value>
      <webElementGuid>5e8f5de2-4e55-44af-807b-105cf4916063</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/span/div/div/div[2]/div/span/span/a</value>
      <webElementGuid>261d6588-7024-495c-b22a-23efb3528cd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/ap/profile/password?ref_=ax_am_landing_change_password&amp;openid.assoc_handle=usflex' and (text() = 'Edit' or . = 'Edit')]</value>
      <webElementGuid>c05550a8-c066-42a3-b1f8-8fea19a5af81</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
