<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_us</name>
   <tag></tag>
   <elementGuidId>8b5e877d-25fe-4993-b8e8-db2f83508cdc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='nav-logo-sprites']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nav-logo-sprites</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bf02db75-39a8-41ef-b20c-1601cda29f2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/ref=nav_logo</value>
      <webElementGuid>d92c2f72-99a2-48b1-a8dc-6bbb96315ec4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nav-logo-sprites</value>
      <webElementGuid>43b8f524-6866-40b3-8609-194009cdde6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-logo-link nav-progressive-attribute</value>
      <webElementGuid>69bc8158-747d-4e1f-8846-74f899dcd31b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Amazon</value>
      <webElementGuid>1e5e8c96-4ff0-40d4-9a1c-82cfc5466cd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
      
      
      .us
    </value>
      <webElementGuid>0711b6b0-70c8-4917-8bf1-5466773b78f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-logo-sprites&quot;)</value>
      <webElementGuid>2b346787-1ac9-449a-a123-9729fa773ba8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='nav-logo-sprites']</value>
      <webElementGuid>3b8e6461-c528-4d2e-acc1-eb74cfc5d0e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-logo']/a</value>
      <webElementGuid>1e82866b-ff4d-4416-95f0-99f40229ea82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skip to main content'])[1]/following::a[1]</value>
      <webElementGuid>4807814c-4c40-4831-8de7-33bfb07291b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deliver to'])[1]/preceding::a[1]</value>
      <webElementGuid>09569078-ea86-464d-9139-fb872beb9bde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/ref=nav_logo')]</value>
      <webElementGuid>27dfb758-11ed-4e1b-b3ac-3976d8d00fb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/a</value>
      <webElementGuid>cd3be40d-3c18-432f-88f5-fe550b854cfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/ref=nav_logo' and @id = 'nav-logo-sprites' and (text() = '
      
      
      .us
    ' or . = '
      
      
      .us
    ')]</value>
      <webElementGuid>31a24044-bd04-4c37-af1d-420dc07e4479</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
