<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Manage your Profiles_home-profile-arrow-icon-0</name>
   <tag></tag>
   <elementGuidId>a3a14439-7eeb-487e-903f-11e9d561eb2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='home-profile-arrow-icon-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#home-profile-arrow-icon-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>3b8981ae-7b1f-4e50-9c33-7de206440b6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>home-profile-arrow-icon-0</value>
      <webElementGuid>1826bdc0-cb41-4ff1-be88-1bb8797827cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-icon a-icon-arrow</value>
      <webElementGuid>9b2615a4-ed44-439f-9adb-076da8121038</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9c2d9b21-424e-404b-9601-21f10a82334e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Arrow icon for profile detail</value>
      <webElementGuid>cc191df4-ab52-4621-95fa-309ff5a25d2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home-profile-arrow-icon-0&quot;)</value>
      <webElementGuid>790f0ae4-3d3e-465d-9238-a6a82f641a6d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='home-profile-arrow-icon-0']</value>
      <webElementGuid>46dd550f-574b-42aa-b631-4a760e2ee2f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='profile-pick-actor-button-0']/a/div/div[2]/i</value>
      <webElementGuid>c2cd8861-44dd-4be8-90b0-6cf774fd6eac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/i</value>
      <webElementGuid>63072efd-2cc3-4c9d-948b-976c0ef3d37d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@id = 'home-profile-arrow-icon-0']</value>
      <webElementGuid>5329560f-f901-48f5-92d5-6668cabbff3f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
