<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_submit.deleteItem</name>
   <tag></tag>
   <elementGuidId>eef24e80-705f-477a-b099-4df7bb32e777</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;submit.deleteItem&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='submit.deleteItem']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f4036508-ec76-4771-a2ce-e9bb332d9fca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>submit.deleteItem</value>
      <webElementGuid>4b0ba2b9-a95f-4ca6-aabe-969ed6fbed4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-action</name>
      <type>Main</type>
      <value>sab:list_c_wl_lv_ov_lig_itemDelete</value>
      <webElementGuid>32410adf-fb5a-411f-95a4-571467b37153</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-item-id</name>
      <type>Main</type>
      <value>0385504209</value>
      <webElementGuid>e354d300-7611-48f4-bdfd-675c1c77c522</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-type</name>
      <type>Main</type>
      <value>action</value>
      <webElementGuid>fe3e971a-d797-4c15-ad73-dff5b8acc615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-input a-declarative</value>
      <webElementGuid>8d29e91b-1dff-4c92-a304-160d682d7b45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>22609c35-f5bb-4144-bd1e-23f4acc0ab87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>delete-button-I33DCY42UJRQQ1-announce</value>
      <webElementGuid>15131b37-96c7-47be-a9e8-aae1e8614764</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-id</name>
      <type>Main</type>
      <value>gatckq-2mqjc4-y223ce-vxjzzx</value>
      <webElementGuid>afe77dd8-7c87-49b4-a63b-f072875c7e24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;delete-button-I33DCY42UJRQQ1&quot;)/span[@class=&quot;a-button-inner&quot;]/input[@class=&quot;a-button-input a-declarative&quot;]</value>
      <webElementGuid>b84c8a37-b13d-4478-99fd-0c8ccf92b14b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='submit.deleteItem']</value>
      <webElementGuid>7559907e-03db-4bfe-8bd1-5ad836b42799</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='delete-button-I33DCY42UJRQQ1']/span/input</value>
      <webElementGuid>62ba8bfa-e1a8-4376-b60c-40a685802cd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/span/span/span/input</value>
      <webElementGuid>f20bc45b-89c4-4d46-8c47-d2cef8ae48ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'submit.deleteItem' and @type = 'submit']</value>
      <webElementGuid>35bf081d-e8ba-4286-ad8f-476793512591</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
